In [4]:
#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

In [5]:
#import and split data
data=load_iris()
x=data.data
y=data.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)



In [6]:
#training & preprocessing
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(x_train, y_train)
out=clf.predict(x_test)
print(out) 

[2 2 0 2 0 1 1 2 1 1 1 1 2 0 1 0 0 0 2 2 0 2 0 0 1 2 0 2 1 2 2 0 0 1 0 2 0
 1 2 0 1 1 1 0 1]


In [7]:
print(x_train)

[[5.4 3.  4.5 1.5]
 [6.  3.  4.8 1.8]
 [5.6 2.8 4.9 2. ]
 [7.  3.2 4.7 1.4]
 [5.8 2.7 4.1 1. ]
 [7.9 3.8 6.4 2. ]
 [6.7 3.3 5.7 2.5]
 [6.9 3.1 4.9 1.5]
 [6.3 2.8 5.1 1.5]
 [5.  3.5 1.6 0.6]
 [5.9 3.  4.2 1.5]
 [4.9 3.  1.4 0.2]
 [5.1 3.4 1.5 0.2]
 [6.5 3.  5.8 2.2]
 [6.5 2.8 4.6 1.5]
 [5.7 4.4 1.5 0.4]
 [4.4 3.  1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [7.2 3.6 6.1 2.5]
 [5.6 3.  4.1 1.3]
 [6.2 2.2 4.5 1.5]
 [6.1 3.  4.9 1.8]
 [6.7 3.1 4.7 1.5]
 [5.5 2.4 3.8 1.1]
 [6.5 3.  5.2 2. ]
 [7.7 2.6 6.9 2.3]
 [6.1 2.8 4.7 1.2]
 [4.7 3.2 1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.6 0.2]
 [6.  2.7 5.1 1.6]
 [7.1 3.  5.9 2.1]
 [6.9 3.1 5.4 2.1]
 [5.5 2.3 4.  1.3]
 [5.2 4.1 1.5 0.1]
 [6.1 2.6 5.6 1.4]
 [6.7 3.  5.  1.7]
 [6.7 2.5 5.8 1.8]
 [6.5 3.  5.5 1.8]
 [5.1 3.5 1.4 0.2]
 [7.7 3.8 6.7 2.2]
 [6.7 3.1 4.4 1.4]
 [6.4 3.2 4.5 1.5]
 [5.8 2.7 5.1 1.9]
 [5.4 3.9 1.3 0.4]
 [5.1 3.7 1.5 0.4]
 [6.8 2.8 4.8 1.4]
 [5.8 2.6 4.  1.2]
 [4.9 3.6 1.4 0.1]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.6 0.4]
 [5.4 3.4 1.7 0.2]
 [6.4 3.2 5.

In [8]:
print(x_test)

[[6.7 3.3 5.7 2.1]
 [6.4 2.8 5.6 2.1]
 [5.2 3.4 1.4 0.2]
 [7.2 3.  5.8 1.6]
 [5.5 3.5 1.3 0.2]
 [5.7 2.9 4.2 1.3]
 [6.6 3.  4.4 1.4]
 [5.9 3.2 4.8 1.8]
 [6.  2.2 4.  1. ]
 [5.7 2.8 4.5 1.3]
 [6.4 2.9 4.3 1.3]
 [5.6 2.5 3.9 1.1]
 [7.7 2.8 6.7 2. ]
 [5.4 3.9 1.7 0.4]
 [5.5 2.5 4.  1.3]
 [4.6 3.6 1.  0.2]
 [4.4 3.2 1.3 0.2]
 [4.8 3.1 1.6 0.2]
 [6.3 3.3 6.  2.5]
 [6.9 3.1 5.1 2.3]
 [5.  3.3 1.4 0.2]
 [6.7 3.1 5.6 2.4]
 [5.8 4.  1.2 0.2]
 [4.9 3.1 1.5 0.2]
 [6.1 3.  4.6 1.4]
 [6.3 2.5 4.9 1.5]
 [5.4 3.7 1.5 0.2]
 [7.2 3.2 6.  1.8]
 [6.2 2.9 4.3 1.3]
 [6.4 2.8 5.6 2.2]
 [7.7 3.  6.1 2.3]
 [4.7 3.2 1.3 0.2]
 [5.7 3.8 1.7 0.3]
 [5.8 2.7 3.9 1.2]
 [4.8 3.  1.4 0.3]
 [6.7 3.  5.2 2.3]
 [5.4 3.4 1.5 0.4]
 [5.7 2.8 4.1 1.3]
 [6.4 3.1 5.5 1.8]
 [4.8 3.4 1.9 0.2]
 [6.1 2.8 4.  1.3]
 [5.7 2.6 3.5 1. ]
 [6.  3.4 4.5 1.6]
 [4.3 3.  1.1 0.1]
 [4.9 2.4 3.3 1. ]]


In [9]:
print(y_train)

[1 2 2 1 1 2 2 1 2 0 1 0 0 2 1 0 0 0 2 1 1 2 1 1 2 2 1 0 0 0 1 2 2 1 0 2 1
 2 2 0 2 1 1 2 0 0 1 1 0 0 0 0 2 1 0 2 0 1 0 1 1 2 0 2 1 0 0 0 1 2 2 0 1 1
 1 0 2 2 0 2 2 0 2 2 2 0 1 1 0 0 0 1 2 1 1 2 2 1 2 0 2 2 0 2 2]


In [10]:
print(y_test)

[2 2 0 2 0 1 1 1 1 1 1 1 2 0 1 0 0 0 2 2 0 2 0 0 1 1 0 2 1 2 2 0 0 1 0 2 0
 1 2 0 1 1 1 0 1]


In [11]:
#evaluting the algorithm
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,out))


[[16  0  0]
 [ 0 15  2]
 [ 0  0 12]]


In [12]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,out))
confusion_matrix(y_test,out)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.88      0.94        17
           2       0.86      1.00      0.92        12

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45



array([[16,  0,  0],
       [ 0, 15,  2],
       [ 0,  0, 12]])

In [13]:
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
clf=KNeighborsClassifier(n_neighbors=5)
cv=KFold(n_splits=12)
scores=cross_val_score(clf,x,y,cv=cv)
print(scores)

[1.         1.         1.         1.         1.         0.69230769
 0.91666667 1.         0.91666667 0.91666667 0.91666667 1.        ]


In [14]:
np.mean(scores)

0.9465811965811964